# Die Pandas Bibliothek

## Überblick

* de facto Standard für Datenanalyse-Programm in Python
* Open Source
    * Lizenzfrei in der Nutzung
    * [Homepage](https://pandas.pydata.org/)
    * [Dokumentation](https://pandas.pydata.org/docs/reference/index.html)
* Funktionsumfang
    * Unterstützung aller gängiger Datenformate, Lesend und Schreibend
    * Spezielle Collection, der DataFrame
    * Unterstützung von Grafiken = Diagrammen
    * Integration der deskriptiven Statistik, also Mittelwerte, Abweichungen, etc.
    * Integration weiterer Bibliotheken, z.B. matplotlib, scikit für Machine Learning

# Installation

In [ ]:
pip install pandas

## Einführung in die Programmierung mit Pandas

### Import

In [2]:
import pandas as pd

### Laden eines CSV-Datensatzes

In [3]:
pd.read_csv('people_data.csv')

     id   firstname lastname  height  weight GENDER
0     1      Stacey   Miller    1.68    92.0      d
1     2       Carla   Gentry    1.68    85.4      d
2     3        Emma  Harding    1.75    98.2      d
3     4    Jeanette    Lopez    1.58    73.8      d
4     5      Edward    White    1.63    68.5      d
..  ...         ...      ...     ...     ...    ...
95   96  Jacqueline   Morris    1.54    99.8      d
96   97       Laura    Smith    1.66    50.1      d
97   98      Steven  Parrish    1.68    99.0      d
98   99     Stephen   Juarez    1.82    93.3      d
99  100    Courtney     Cruz    1.59    75.1      d

[100 rows x 6 columns]

### Laden des Datensatzen und Zuweisung an eine Variable

* Typ der Variablen ist ein Pandas-DataFrame

In [5]:
df = pd.read_csv('people_data.csv')
df

     id   firstname lastname  height  weight GENDER
0     1      Stacey   Miller    1.68    92.0      d
1     2       Carla   Gentry    1.68    85.4      d
2     3        Emma  Harding    1.75    98.2      d
3     4    Jeanette    Lopez    1.58    73.8      d
4     5      Edward    White    1.63    68.5      d
..  ...         ...      ...     ...     ...    ...
95   96  Jacqueline   Morris    1.54    99.8      d
96   97       Laura    Smith    1.66    50.1      d
97   98      Steven  Parrish    1.68    99.0      d
98   99     Stephen   Juarez    1.82    93.3      d
99  100    Courtney     Cruz    1.59    75.1      d

[100 rows x 6 columns]

### Exploration des Datensatzes

* head() und tail()
    * Standardgröße ist 5
    * head(3)

In [7]:
df.head(3)

   id firstname lastname  height  weight GENDER
0   1    Stacey   Miller    1.68    92.0      d
1   2     Carla   Gentry    1.68    85.4      d
2   3      Emma  Harding    1.75    98.2      d

* Info und Describe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     100 non-null    float64
 4   weight     100 non-null    float64
 5   GENDER     100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB

In [9]:
df.describe()

               id      height      weight
count  100.000000  100.000000  100.000000
mean    50.500000    1.739100   77.210000
std     29.011492    0.135945   13.929342
min      1.000000    1.510000   50.100000
25%     25.750000    1.627500   68.250000
50%     50.500000    1.755000   77.000000
75%     75.250000    1.830000   89.700000
max    100.000000    1.990000   99.900000

* Unsaubere Eingangsdaten

In [ ]:
dirty_df = pd.read_csv('people_data_dirty.csv')
dirty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     98 non-null     float64
 4   weight     98 non-null     float64
 5   GENDER     100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB

In [ ]:
dirty_df = pd.read_csv('people_data_very_dirty.csv') #height manipuliert --> "1.92xxx" - Dtype wird zu object
dirty_df.info()

### DataFrame als Datencontainer / Collection

* Elementare Berechnungen / Zugriffe

In [ ]:
height_series = df['height'] + 1
print(height_series)

In [ ]:
df['weight']/(df['height']**2) #BMI Berechnung

0     32.596372
1     30.257937
2     32.065306
3     29.562570
4     25.781926
        ...
95    42.081295
96    18.181158
97    35.076531
98    28.166888
99    29.706103
Length: 100, dtype: float64

In [23]:
bmi = df['weight']/(df['height']**2)
bmi

0     32.596372
1     30.257937
2     32.065306
3     29.562570
4     25.781926
        ...
95    42.081295
96    18.181158
97    35.076531
98    28.166888
99    29.706103
Length: 100, dtype: float64

In [24]:
bmi.info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: None
Non-Null Count  Dtype
--------------  -----
100 non-null    float64
dtypes: float64(1)
memory usage: 932.0 bytes

In [25]:
bmi.describe()

count    100.000000
mean      25.889153
std        5.793465
min       13.295885
25%       22.496651
50%       24.580322
75%       29.796879
max       42.081295
dtype: float64

* Zuweisung einer Series an einen DataFrame

In [26]:
df['bmi'] = df['weight']/(df['height']**2) #BMI Spalte hinzugefügt
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     100 non-null    float64
 4   weight     100 non-null    float64
 5   GENDER     100 non-null    object
 6   bmi        100 non-null    float64
dtypes: float64(3), int64(1), object(3)
memory usage: 5.6+ KB

* Entfernen einer Series aus einem DataFrame