# Books Daten von json

### Import Pandas

In [1]:
import pandas as pd

### Read DataFrame

In [2]:
url = 'https://raw.githubusercontent.com/ozlerhakan/mongodb-json-files/master/datasets/books.json'
books = pd.read_json(url, lines=True)
books

,_id,title,isbn,pageCount,publishedDate,thumbnailUrl,shortDescription,longDescription,status,authors,categories
0,1,Unlocking Android,1933988673,416,{'$date': '2009-04-01T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,Unlocking Android: A Developer's Guide provide...,Android is an open source mobile phone platfor...,PUBLISH,"[W. Frank Ableson, Charlie Collins, Robi Sen]","[Open Source, Mobile]"
1,2,"Android in Action, Second Edition",1935182722,592,{'$date': '2011-01-14T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,"Android in Action, Second Edition is a compreh...","When it comes to mobile apps, Android can do a...",PUBLISH,"[W. Frank Ableson, Robi Sen]",[Java]
2,3,Specification by Example,1617290084,0,{'$date': '2011-06-03T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[Gojko Adzic],[Software Engineering]
3,4,Flex 3 in Action,1933988746,576,{'$date': '2009-02-02T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,New web applications require engaging user-fri...,PUBLISH,"[Tariq Ahmed with Jon Hirschi, Faisal Abid]",[Internet]
4,5,Flex 4 in Action,1935182420,600,{'$date': '2010-11-15T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,"Using Flex, you can create high-quality, effec...",PUBLISH,"[Tariq Ahmed, Dan Orlando, John C. Bland II, J...",[Internet]
...,...,...,...,...,...,...,...,...,...,...,...
426,{'$oid': '53c2ae8528d75d572c06adb8'},DSLs in Action,1935182455,376,{'$date': '2010-12-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,DSLs in Action introduces the concepts and def...,"On any given day, a developer may encounter a ...",PUBLISH,[],[]
427,{'$oid': '53c2ae8528d75d572c06adb9'},Database Programming for Handheld Devices,1884777856,0,{'$date': '2000-07-01T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[],[]
428,{'$oid': '53c2ae8528d75d572c06adba'},Jakarta Commons Online Bookshelf,1932394524,402,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,Written for developers and architects with rea...,PUBLISH,[],[]
429,{'$oid': '53c2ae8528d75d572c06adbb'},Browsing with HttpClient,1932394524a-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,Written for developers and architects with rea...,NaN,PUBLISH,[],[]
430,{'$oid': '53c2ae8528d75d572c06adbc'},Codec: Encoders and Decoders,1932394524j-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[],[]

### Spalten und deren Type Infos

In [3]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               431 non-null    object
 1   title             431 non-null    object
 2   isbn              428 non-null    object
 3   pageCount         431 non-null    int64
 4   publishedDate     353 non-null    object
 5   thumbnailUrl      411 non-null    object
 6   shortDescription  160 non-null    object
 7   longDescription   263 non-null    object
 8   status            431 non-null    object
 9   authors           431 non-null    object
 10  categories        431 non-null    object
dtypes: int64(1), object(10)
memory usage: 37.2+ KB

### Beschreibung von der numerischen Spalten

In [4]:
books.describe()

         pageCount
count   431.000000
mean    289.259861
std     260.873349
min       0.000000
25%       0.000000
50%     350.000000
75%     475.000000
max    1101.000000

### Categorise with page count

In [5]:
books[books['pageCount'] == 0]

,_id,title,isbn,pageCount,publishedDate,thumbnailUrl,shortDescription,longDescription,status,authors,categories
2,3,Specification by Example,1617290084,0,{'$date': '2011-06-03T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[Gojko Adzic],[Software Engineering]
15,17,MongoDB in Action,1935182870,0,{'$date': '2011-12-12T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,MongoDB In Action is a comprehensive guide to ...,MongoDB is a document-oriented database that's...,PUBLISH,[Kyle Banker],[Next Generation Databases]
64,74,SOA Governance in Action,1617290270,0,{'$date': '2012-07-27T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[Jos Dirksen],[java]
69,117,Managing Components with Modeler,1932394524k-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[Vikram Goyal],[Java]
70,118,Command-line Processing with CLI,1932394524l-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[Vikram Goyal],[Java]
...,...,...,...,...,...,...,...,...,...,...,...
403,{'$oid': '53c2ae8528d75d572c06ada1'},The Well-Grounded Java Developer,1617290068,0,{'$date': '2012-07-10T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,The Well-Grounded Java Developer is a unique g...,The Java community has always been dynamic and...,PUBLISH,[],[]
418,{'$oid': '53c2ae8528d75d572c06adb0'},Hello! iOS Development,1935182986,0,{'$date': '2013-07-28T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[],[]
427,{'$oid': '53c2ae8528d75d572c06adb9'},Database Programming for Handheld Devices,1884777856,0,{'$date': '2000-07-01T00:00:00.000-0700'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[],[]
429,{'$oid': '53c2ae8528d75d572c06adbb'},Browsing with HttpClient,1932394524a-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,Written for developers and architects with rea...,NaN,PUBLISH,[],[]
430,{'$oid': '53c2ae8528d75d572c06adbc'},Codec: Encoders and Decoders,1932394524j-e,0,{'$date': '2005-03-01T00:00:00.000-0800'},https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ....,NaN,NaN,PUBLISH,[],[]

## Books upto 250 pages

In [6]:
selection_vector = (books['pageCount'] > 0) & (books['pageCount'] < 250)
selection_vector

0      False
1      False
2      False
3      False
4      False
       ...
426    False
427    False
428    False
429    False
430    False
Name: pageCount, Length: 431, dtype: bool

* Books category with pageCount
  * 0 Pages -> "Info Missing"
  * upto 300 -> "Small"
  * 301 to 700 -> "Medium"
  * more than 700 -> "Large

In [7]:
books['bookSize'] = 'Info Missing'  # default

books.loc[(books['pageCount'] > 0) & (books['pageCount'] <= 300), 'bookSize'] = 'Small'
books.loc[(books['pageCount'] > 300) & (books['pageCount'] <= 700), 'bookSize'] = 'Medium'
books.loc[(books['pageCount'] > 700), 'bookSize'] = 'Large'
books['bookSize']

0            Medium
1            Medium
2      Info Missing
3            Medium
4            Medium
           ...
426          Medium
427    Info Missing
428          Medium
429    Info Missing
430    Info Missing
Name: bookSize, Length: 431, dtype: object